name : appollo ci

on: ['push']

jobs:
  check_validity_flutter:
    runs-on: [runner_nathan_label]
    name: "Test phase" 
    steps:
      # extract repo
      - name: Checkout
        run: echo 'test flutter'
        # uses: actions/checkout@v3

      - name: Run unite test
        run: echo 'test flutter'
        # run: flutter test 


  build_ipa:
    needs: check_validity_flutter
    runs-on: [runner_nathan_label]
    name: "Build IPA file"
    if: github.ref != 'refs/heads/production'
    steps:
      - name: Install Appollo
        run : echo "Install step"
        # run: yes | pip3 install appollo

      - name: Connection
        run : echo "Connection step"
        # run : appollo signin --email <email> --password <password>

      - name: Building the IPA
        run: echo 'build ipa'
        # run: appollo build start --build-type=ad-hoc <application_key>

      - name: Disconnection
        run : echo "Disconnection step"
        # run : appollo signout

  deploy:
    needs: build_ipa
    runs-on: [runner_nathan_label]
    name: "Publication app" 
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Install Appollo
        run : echo "Install step"
        # run: yes | pip3 install appollo

      - name: Connection
        run : echo "Connection step"
        # run : appollo signin --email <email> --password <password>

      - name: Publication
        run : echo "on publie"
        #run: appollo build start --build-type=publication <application_key>
      
      - name: Disconnection
        run : echo "Disconnection step"
        # run : appollo signout

