name : appollo ci

#Controls when the workflow will run (merge on main and pull request on main)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #name of job
  check_validity_flutter:

    # chose the runner (personal runner in this case)
    runs-on: [runner_nathan_label]

    #name of this workflow
    name: "check step" 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run test script
        run: flutter test

      - name: appollo ls
        run: appollo build ls
