name : appollo ci

#Controls when the workflow will run (merge on main and pull request on main)
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on: ['push']

jobs:
  #name of job
  check_validity_flutter:

    # chose the runner (personal runner in this case)
    runs-on: [runner_nathan_label]

    #name of this workflow
    name: "test" 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unite test
        # run: flutter test
        run: echo "${{ github.event.inputs.environment }}"
      
  build_ipa:

    runs-on: [runner_nathan_label]

    name: "build" 
    steps:
      - name: Connection
        # run : appollo signin --email <email> --password <password>
        run : echo "Connection step"

      - name: Building the IPA
        run: appollo build start --build-type=ad-hoc 882
        # run: appollo build start --build-type=ad-hoc <application_key>

      - name: Disconnection
      #   run : appollo signout
        run : echo "Disconnection step"

