name : appollo ci

#Controls when the workflow will run (merge on main and pull request on main)
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on: ['push']

jobs:
  #name of job
  check_validity_flutter:

    # chose the runner (personal runner in this case)
    runs-on: [runner_nathan_label]

    #name of this workflow
    name: "build" 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unite test
        run: flutter test

      - name: Building the IPA
        run: appollo build start
